import streamlit as st


st.title("Privacy Policy")
st.write("**Effective Date:** February 10, 2025")

st.write("""
Mail-It is committed to protecting your privacy. This Privacy Policy explains how we handle your information when you use our AI-powered email-sending service. Importantly, we do not collect, store, or share any personal data. By using Mail-It, you agree to the terms outlined in this policy.
""")

st.header("1. No Data Collection")
st.write("""
Mail-It does not collect, store, or process any personal data from its users. Specifically:

- We do not save your Google account information, including email addresses or authentication tokens.
- We do not store the content of emails generated by our AI.
- We do not track or log your usage of the application.

All operations are performed in real-time and are not retained once processed.
""")

st.header("2. Google Authentication")
st.write("""
Mail-It uses Google's OAuth authentication to allow you to send emails via your Google account. This process is managed securely by Google, and Mail-It does not access or store your credentials. You can revoke Mail-It's access at any time through your Google account settings.
""")

st.header("3. AI Email Generation")
st.write("""
The email content generated by Mail-It's AI is processed in real-time and is not stored or retained after it is sent. The generated content remains under your control and is not accessible to us.
""")

st.header("4. Data Security")
st.write("""
Although we do not collect or store data, we prioritize security when processing your requests:

- All communication between Mail-It and external services (e.g., Google) is encrypted using industry-standard protocols.
- Your data remains within your control and is only used to fulfill the specific task of generating and sending emails.
""")

st.header("5. Third-Party Services")
st.write("""
Mail-It integrates with third-party services like Google for authentication and email sending. These services may have their own privacy policies governing how they handle your data. We recommend reviewing Google's Privacy Policy for more information:
""")
st.markdown("[Google Privacy Policy](https://policies.google.com/privacy)")

st.header("6. Your Choices")
st.write("""
Since we do not collect or store any user data, there are no additional actions required from you to protect your privacy while using Mail-It. However, you can revoke Mail-It's access to your Google account at any time through your Google account settings.
""")

st.header("7. Children's Privacy")
st.write("""
Mail-It is not intended for individuals under the age of 13. As we do not collect any data, we cannot knowingly collect information from children.
""")

st.header("8. Changes to This Privacy Policy")
st.write("""
We may update this Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. Any updates will be posted on this page with an updated effective date.
""")

st.header("Contact Us")
st.write("""
If you have any questions about this Privacy Policy or how Mail-It operates, please contact us at:

**Email:** viswanathanganesh24@gmail.com\n
**Website:** mail-it.streamlit.app
""")

